{% set version = "22.03" %}

package:
  name: nvidia-apex
  version: {{ version }}

source:
  url: https://github.com/NVIDIA/apex/archive/refs/tags/{{ version }}.tar.gz
  sha256: 694f1ac1aaed6435b2f0c2ebc1af56b8a215a5eaa96c2565a578e8734378ff66
  patches:
    # https://github.com/NVIDIA/apex/pull/1588
    # https://github.com/NVIDIA/apex/commit/6943fd26e04c59327de32592cf5af68be8f5c44e
    - 0001-use-torch.tensor-to-create-a-tensor-with-initializer.patch

build:
  number: 4
  skip: true  # [not linux or cuda_compiler == "None"]
  string: cuda{{ cuda_compiler_version | replace('.', '') }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
  script_env:
    - TORCH_CUDA_ARCH_LIST=3.5;5.0;6.0;6.1;7.0;7.5;8.0;8.6+PTX  # [cuda_compiler_version == "11.2"]
  script:
    - python -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
  host:
    - python
    - pytorch
    - pytorch =*=cuda*
    - setuptools
    - pip
  run:
    - python
    - cxxfilt
    - tqdm
    - numpy
    - PyYAML
    - pytest
  run_constrained:
    - pytorch =*=cuda*

test:
  imports:
    - apex
    - apex.amp
    - apex.parallel
    - apex.optimizers
    - apex.normalization.fused_layer_norm

about:
  home: "https://nvidia.github.io/apex/"
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "a Pytorch extension with NVIDIA-maintained utilities to streamline mixed precision and distributed training."
  doc_url: "https://nvidia.github.io/apex/"
  dev_url: "https://github.com/NVIDIA/apex"

extra:
  recipe-maintainers:
    - h-vetinari
    - oblute
    - benhuff
    - jakirkham
    - rluria14
